// Code generated by "stringer -type=VPNState"; DO NOT EDIT

package main

import "fmt"

const _VPNState_name = "VPNLaunchingVPNConnectingVPNRetryingVPNConnectedVPNExitingVPNExited"

var _VPNState_index = [...]uint8{0, 12, 25, 36, 48, 58, 67}

func (i VPNState) String() string {
	if i < 0 || i >= VPNState(len(_VPNState_index)-1) {
		return fmt.Sprintf("VPNState(%d)", i)
	}
	return _VPNState_name[_VPNState_index[i]:_VPNState_index[i+1]]
}
